@extends('layouts.app')

@section('content')
<div class="container-lg">
    <div class="row">
        <div class="col-6">
            <p> Legenda o káve Tá hovorí, že si pastier Kaldi, ktorý priviedol svoje stádo kôz na pastvu do etiópskych kopcov všimol, že po spasení listov a bobúľ z určitého kríka začali byť niektoré zvieratá nekľudné a podráždené. Tieto zvláštne účinky ho veľmi prekvapili, a tak sa rozhodol, že plody tejto rastliny sám vyskúša. Kaldi objavil ich povzbudzujúce účinky a nazbieral niekoľko plodov , ktoré doniesol do neďalekého kláštora. Mnísi ale nad týmto objavom nejavili žiadne nadšenie a zo strachu, že ide o plody diabla, nahádzali bobule do ohňa.  A v tom okamžiku sa stal zázrak – z ohňa sa začala šíriť nádherná vôňa, ktorá mníchov prinútila zmeniť názor a ušetriť túto rastlinu krutého osudu. Boli to práve mnísi, ktorí prišli na nápad pripraviť z týchto plodov nápoj a tak sa diablove plody zázračne premenili na dar boží, ktorý mníchom pomáhal zostávať hore v dlhých nočných modlitbách.
                Káva sa po moslimských krajinách rozšírila ako prijateľná náhrada za Koránom zakázaný alkohol. Ale oficiálne prijatie nastalo až vtedy, keď došlo k záchrane proroka Mohameda v okamžiku, kedy začal zaspávať pri modlitbách. Podľa povestí mu archanjel Gabriel dal trochu kávy zoslanej z neba. Po niekoľkých dúškoch získal Mohamed dostatok sily, aby mohol "vyhodiť zo sedla štyridsať jazdcov a obšťastniť štyridsať žien". Arabi boli prví, ktorý začali variť zrná vytiahnuté z plodov – zelené zrná upražili a rozomleli. Nie náhodou pochádza slovo káva z arabského slova "quahwa" označujúcého akýkoľvek zeleninový nápoj.
                Povesť o tom, ako sa káva dostala na Západ, má dve odlišné verzie. Podľa jednej z nich zanechali Turci, utekajúci od brán Viedne v roku 1683, vo svojom tábore päťsto vriec týchto vzácnych zŕn. Podľa inej verzie začali kávu do Európy dovážať benátsky kupci v roku 1615. Tí ju najprv predávali lekárnikom ako "zázračný liek", a potom verejnosti ako nápoj určený k pochuteniu s priateľmi.
                Benátčania okolo roku 1624 ovládali techniku praženia a k dokonalosti ju doviedli v „obchodoch s vodou a ľadom", v ktorých sa tradične podávali ľadové a vodu obsahujúce nápoje. Nebola to vtedy náhoda, že sa okolo roku 1645 začalo týmto podnikom hovoriť „kaviarne". Obľuba tohto nápoja sa neskôr rozšírila do všetkých kútov Európy a Benátky sa stali dodávateľom surovín pre susedné krajiny.
            </p>
        </div>
        <div class="col-6">
            <p> Obchodné korene rodiny Molinari siahajú do začiatku 19. storočia, kedy v roku 1804 v talianskom meste  Modena Giuseppe Molinari, dovtedy pôsobiaci v potravinárskom sektore, začína obchodovať s kávou a zakladá firmu  Molinari. Káva Molinari  je dnes známa na každom kontinente,  milovali ju aj na kráľovskom dvore Savoia. Svoju kaviareň "Bar Molinari" rodina postavila na Via Emilia v talianskej Modene v roku 1911. Rovnako ako staré kaviarne, zriadené v Taliansku počas 19. storočia, stala sa aj kaviareň rodiny Molinari preslávená ako miesto stretávania sa intelektuálov v tomto živom meste v údolí rieky Pád. Je zaujímavé, že "Bar Molinari" sa stal známym a zapísal sa do histórie s moderným názvom "bar" a tým upustil od dovtedy typického názvu 18. storočia, názvu "Café". V roku 1944 sa začali Giuseppe a jeho synovia Alberto a Emilio  intenzívne zaoberať rozvojom svojej firmy. Prinieslo to rast produkcie kávy praženej vlastnej pražiarni, množstvo ocenení kvality, stále nových a nových zákazníkov. Spoločnosť sa doteraz nachádza v historickom centre mesta Modena  na  Via Modonella.

                Vyznačuje sa lahodnou a jemnou chuťou, dokonalou arómou a úžasnou cremou. Všetky tieto charakteristiky získava káva nie len svojim exkluzívnym pôvodom ale tiež technológiami, na ktorých si spoločnsoť veľmi zakladá a neustále sa ich snaží vylepšovať. Ak si potrpíte na naozaj kvalitnú kávu s chuťou tradície, Molinari je tu pre vás.  Káva, ktorá si vás získa chuťou, vôňou ale tiež svojim prístupom. Spoločnosť sa totiž snaží približovať sa svojim zákazníkom a prinášať im viac ako len kávu. Prináša im potešenie, pocit, že káva nie je len nápoj. Pre mnohých z nás je totiž pitie kávy rituálom, ktorým začíname či už týždeň alebo víkend. Ak je treba, tento zázračný nápoj nás povzbudí do náročného dňa a na druhej strane, vďaka nemu dokonale zrelaxujeme a uvoľníme všetky naše zmysly po náročnom dni v práci.
            </p>
        </div>
    </div>
</div>
@endsection
